language: node_js
node_js:
  - "10"
addons:
  chrome: stable
sudo: required
before_script:
  -  npm install -g parcel-bundler
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"